import React, { useEffect } from "react";
import { Container, Typography } from "@mui/material";

const AboutComponent: React.FC = () => {
  useEffect(() => {
    const script = document.createElement("script");
    script.src = "https://cdnjs.buymeacoffee.com/1.0.0/button.prod.min.js";
    script.setAttribute("data-name", "bmc-button");
    script.setAttribute("data-slug", "doyled.it");
    script.setAttribute("data-color", "#FFDD00");
    script.setAttribute("data-emoji", "☕");
    script.setAttribute("data-font", "Cookie");
    script.setAttribute("data-text", "Buy me a Red Bull");
    script.setAttribute("data-outline-color", "#000000");
    script.setAttribute("data-font-color", "#000000");
    script.setAttribute("data-coffee-color", "#ffffff");
    script.async = true;

    document.body.appendChild(script);

    return () => {
      document.body.removeChild(script);
    };
  }, []);

  return (
    <Container style={{ padding: "20px" }}>
      <Typography variant="h4" component="h1" gutterBottom>
        About
      </Typography>
      <Typography variant="body1" paragraph>
        <i>Lawyer Brain</i> is a retrieval augmented generation (RAG) Chatbot
        that uses the transcripts from the{" "}
        <a href="https://www.fivefourpod.com/" target="_blank" rel="noreferrer">
          Five Four Podcast
        </a>{" "}
        to inform the answers generated by the large language model (LLM).
      </Typography>
      <Typography variant="body1" paragraph>
        This project is a labor of love and labor of necessity because 5-4 is my
        favorite podcast and I simply don't have the brainpower to remember all
        the great arguments and references that Rhiannon, Peter, and Michael
        make. So, I made this second robot brain to get a little smarter.
      </Typography>
      <Typography variant="body1" paragraph>
        For those interested, I use FastAPI, LangChain, and Chroma DB for the
        backend, and React on the frontend. I host the backend API on Heroku,
        Chroma on GCP's Cloud Run with a storage bucket volume for the database
        contents. And I host the frontend on GitHub Pages. This seems to be the
        cheapest option that I could find.
      </Typography>
      <Typography variant="body1" paragraph>
        If you have a bug to report, open an{" "}
        <a
          href="https://github.com/doyled-it/lawyer-brain/issues"
          target="_blank"
          rel="noreferrer"
        >
          issue
        </a>
        . And if you have a feature request, start a{" "}
        <a
          href="https://github.com/doyled-it/lawyer-brain/discussions"
          target="_blank"
          rel="noreferrer"
        >
          discussion
        </a>
        !
      </Typography>
      <Typography variant="body1" paragraph>
        Check out my other projects on{" "}
        <a href="https://doyled-it.com/" target="_blank" rel="noreferrer">
          doyled-it.com
        </a>
        .
      </Typography>
      <Typography variant="body1" paragraph>
        Created with{" "}
        <span role="img" aria-label="heart">
          ❤️
        </span>{" "}
        by{" "}
        <a href="https://github.com/doyled-it" target="_blank" rel="noreferrer">
          @doyled-it
        </a>{" "}
        on GitHub.
      </Typography>
      <div style={{ textAlign: "center", marginTop: "20px" }}>
        <a
          href="https://www.buymeacoffee.com/doyled.it"
          className="bmc-button"
          target="_blank"
          rel="noopener noreferrer"
        >
          <img
            src="https://cdn.buymeacoffee.com/buttons/v2/default-yellow.png"
            alt="Buy me a Red Bull"
            style={{ height: "60px", width: "217px" }}
          />
        </a>
      </div>
    </Container>
  );
};

export default AboutComponent;
